<?php

use Carbon\Carbon as Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Class RelatedInlineTableSeeder
 */
class RelatedInlineTableSeeder extends Seeder
{
    public function run()
    {
        $now = Carbon::now();

        /**
         * create failure table seeder
         */
        $table_name = 'inline_types';

        if (env('DB_CONNECTION') == 'mysql') {
            DB::connection('950A')->statement('SET FOREIGN_KEY_CHECKS=0;');
        }

        // if (env('DB_CONNECTION') == 'mysql') {
        //     DB::connection('950A')->table($table_name)->truncate();
        // } elseif (env('DB_CONNECTION') == 'sqlite') {
        //     DB::connection('950A')->statement('DELETE FROM ' . $table_name);
        // } else {
        //     //For PostgreSQL or anything else
        //     DB::connection('950A')->statement('TRUNCATE TABLE ' . $table_name . ' CASCADE');
        // }

        $figures = collect(DB::connection('950A')
            ->table('figures')
            ->where('inspection', '=', 'inline')
            ->select(['id', 'pt_pn', 'process'])
            ->get());

        $getFigureId = function($pn, $process) use($figures) {
            return $figures->first(function($key, $value) use ($pn, $process) {
                return $value->pt_pn === $pn && $value->process === $process;
            })->id;
        };

        $data = [
            //成形：精度検査：ドアインナR + リンフォースR
            [
                'x'          => 1529,
                'y'          => 341,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 1,
                'position'   => 'H14',
                'min'        => -0.9,
                'max'        => 1.6,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1075,
                'y'          => 581,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 2,
                'position'   => 'L22',
                'min'        => -2.5,
                'max'        => 0.7,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 865,
                'y'          => 578,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 3,
                'position'   => 'L25',
                'min'        => -1.2,
                'max'        => 1.8,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 323,
                'y'          => 110,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 4,
                'position'   => 'H16+75',
                'min'        => -1,
                'max'        => 0.9,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 379,
                'y'          => 377,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 5,
                'position'   => 'H13',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 335,
                'y'          => 255,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 6,
                'position'   => 'H14+50',
                'min'        => -1.3,
                'max'        => 0.9,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 323,
                'y'          => 160,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 7,
                'position'   => 'H15+50',
                'min'        => -0.8,
                'max'        => 1.1,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 794,
                'y'          => 83,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 8,
                'position'   => 'L25+19',
                'min'        => -2,
                'max'        => 0.9,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1073,
                'y'          => 94,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 9,
                'position'   => 'L21+91',
                'min'        => -1.6,
                'max'        => 1.2,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 353,
                'y'          => 296,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 10,
                'position'   => 'L19+20',
                'min'        => -3.2,
                'max'        => 0.8,
                'pt_pn'      => 6715111020,
                'figure_id'  => $getFigureId(6715111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1115,
                'y'          => 246,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 11,
                'position'   => 'L26+76',
                'min'        => -1.2,
                'max'        => 2.2,
                'pt_pn'      => 6715111020,
                'figure_id'  => $getFigureId(6715111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1419,
                'y'          => 236,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 12,
                'position'   => 'L29+75',
                'min'        => -1.6,
                'max'        => 1.2,
                'pt_pn'      => 6715111020,
                'figure_id'  => $getFigureId(6715111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 532,
                'y'          => 162,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 13,
                'position'   => 'L211+91.3',
                'min'        => -1.6,
                'max'        => 2.2,
                'pt_pn'      => 6715111020,
                'figure_id'  => $getFigureId(6715111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1137,
                'y'          => 110,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 14,
                'position'   => 'L26+76.2',
                'min'        => -1.7,
                'max'        => 3.9,
                'pt_pn'      => 6715111020,
                'figure_id'  => $getFigureId(6715111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 78,
                'y'          => 84,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 15,
                'position'   => 'H16+75',
                'min'        => -0.8,
                'max'        => 0.3,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 108,
                'y'          => 394,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 16,
                'position'   => 'H13',
                'min'        => -0.8,
                'max'        => 0,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 88,
                'y'          => 259,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 17,
                'position'   => 'H14+50',
                'min'        => -0.5,
                'max'        => 0.3,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 78,
                'y'          => 132,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 18,
                'position'   => 'H15+50',
                'min'        => -0.4,
                'max'        => 0.2,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1353,
                'y'          => 449,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'right',
                'label'      => 19,
                'position'   => 'H12+80',
                'min'        => -1,
                'max'        => 0.3,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 485,
                'y'          => 298,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 20,
                'position'   => 'H14+20',
                'min'        => -1.7,
                'max'        => 0.1,
                'pt_pn'      => 6714111020,
                'figure_id'  => $getFigureId(6714111020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],
            //成形：精度検査：ドアインナL + リンフォースL
            [
                'x'          => 197,
                'y'          => 341,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 1,
                'position'   => 'H14',
                'min'        => -1,
                'max'        => 1.6,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 651,
                'y'          => 581,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 2,
                'position'   => 'L22',
                'min'        => -2.4,
                'max'        => 0.8,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 861,
                'y'          => 578,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 3,
                'position'   => 'L25',
                'min'        => -0.6,
                'max'        => 1.5,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1403,
                'y'          => 110,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 4,
                'position'   => 'H16+75',
                'min'        => -0.7,
                'max'        => 1.2,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1347,
                'y'          => 377,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 5,
                'position'   => 'H13',
                'min'        => -1,
                'max'        => 0.8,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1391,
                'y'          => 255,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 6,
                'position'   => 'H14+50',
                'min'        => -1.2,
                'max'        => 1.0,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1403,
                'y'          => 160,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 7,
                'position'   => 'H15+50',
                'min'        => -1,
                'max'        => 1.2,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 932,
                'y'          => 83,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 8,
                'position'   => 'L25+19',
                'min'        => -2.8,
                'max'        => 1,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 653,
                'y'          => 94,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 9,
                'position'   => 'L21+91',
                'min'        => -2.3,
                'max'        => 0.8,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1373,
                'y'          => 296,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 10,
                'position'   => 'L19+20',
                'min'        => -3.1,
                'max'        => 1.4,
                'pt_pn'      => 6715211020,
                'figure_id'  => $getFigureId(6715211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 611,
                'y'          => 246,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 11,
                'position'   => 'L26+76',
                'min'        => -1.7,
                'max'        => 2.1,
                'pt_pn'      => 6715211020,
                'figure_id'  => $getFigureId(6715211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 307,
                'y'          => 236,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 12,
                'position'   => 'L29+75',
                'min'        => -3.2,
                'max'        => 1.4,
                'pt_pn'      => 6715211020,
                'figure_id'  => $getFigureId(6715211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1194,
                'y'          => 162,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 13,
                'position'   => 'L211+91.3',
                'min'        => -0.4,
                'max'        => 2.2,
                'pt_pn'      => 6715211020,
                'figure_id'  => $getFigureId(6715211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 589,
                'y'          => 110,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 14,
                'position'   => 'L26+76.2',
                'min'        => -1,
                'max'        => 3.4,
                'pt_pn'      => 6715211020,
                'figure_id'  => $getFigureId(6715211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1648,
                'y'          => 84,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 15,
                'position'   => 'H16+75',
                'min'        => -0.9,
                'max'        => 0.4,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1618,
                'y'          => 394,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 16,
                'position'   => 'H13',
                'min'        => -0.8,
                'max'        => 0,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1638,
                'y'          => 259,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 17,
                'position'   => 'H14+50',
                'min'        => -0.9,
                'max'        => 0.2,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1648,
                'y'          => 132,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 18,
                'position'   => 'H15+50',
                'min'        => -0.5,
                'max'        => 0.7,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 373,
                'y'          => 449,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 19,
                'position'   => 'H12+80',
                'min'        => -1.2,
                'max'        => 0.2,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1241,
                'y'          => 298,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 20,
                'position'   => 'H14+20',
                'min'        => -1.4,
                'max'        => 0.4,
                'pt_pn'      => 6714211020,
                'figure_id'  => $getFigureId(6714211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],
            //成形：精度検査：ラゲージインナSTD
            [
                'x'          => 255,
                'y'          => 260,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 1,
                'position'   => 'W5L+50',
                'min'        => -1,
                'max'        => 0.4,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 175,
                'y'          => 360,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 2,
                'position'   => 'L42',
                'min'        => -1,
                'max'        => 0.4,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 105,
                'y'          => 480,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 3,
                'position'   => 'L44+80',
                'min'        => -0.5,
                'max'        => 0.9,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 435,
                'y'          => 710,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 4,
                'position'   => 'W3L',
                'min'        => -3.5,
                'max'        => 1.5,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 805,
                'y'          => 750,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 5,
                'position'   => 'W0',
                'min'        => -5,
                'max'        => 0,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1199,
                'y'          => 730,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 6,
                'position'   => 'W3R',
                'min'        => -3.5,
                'max'        => 1.5,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1609,
                'y'          => 560,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 7,
                'position'   => 'L44+80',
                'min'        => -0.55,
                'max'        => 0.85,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1629,
                'y'          => 420,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 8,
                'position'   => 'L42',
                'min'        => -0.95,
                'max'        => 0.45,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1619,
                'y'          => 310,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 9,
                'position'   => 'W5R+50',
                'min'        => -1,
                'max'        => 0.4,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 909,
                'y'          => 310,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 10,
                'position'   => 'W0',
                'min'        => -2,
                'max'        => 2,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 259,
                'y'          => 540,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 11,
                'position'   => 'W5L',
                'min'        => -3,
                'max'        => 1,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 813,
                'y'          => 693,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 12,
                'position'   => 'W0',
                'min'        => -4,
                'max'        => 1,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1443,
                'y'          => 623,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 13,
                'position'   => 'W5R',
                'min'        => -3,
                'max'        => 1,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 105,
                'y'          => 580,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 14,
                'position'   => 'H16+40',
                'min'        => -0.5,
                'max'        => 2.5,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1599,
                'y'          => 630,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 15,
                'position'   => 'H16+40',
                'min'        => -0.5,
                'max'        => 2.5,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 255,
                'y'          => 438,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 16,
                'position'   => 'L44',
                'min'        => -3,
                'max'        => 1,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1531,
                'y'          => 487,
                'lx'         => 0,
                'ly'         => 0,
                'side'       => 'left',
                'label'      => 17,
                'position'   => 'L44',
                'min'        => -3,
                'max'        => 1,
                'pt_pn'      => 6441211010,
                'figure_id'  => $getFigureId(6441211010, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],
            //成形：精度検査：ラゲージインナSTD
            [
                'x'          => 255,
                'y'          => 260,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 1,
                'position'   => 'W5L+50',
                'min'        => -1,
                'max'        => 0.4,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 175,
                'y'          => 360,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 2,
                'position'   => 'L42',
                'min'        => -9.5,
                'max'        => 0.45,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 105,
                'y'          => 480,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 3,
                'position'   => 'L44+80',
                'min'        => -0.45,
                'max'        => 0.95,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 435,
                'y'          => 710,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 4,
                'position'   => 'W3L',
                'min'        => -3.5,
                'max'        => 1.5,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 805,
                'y'          => 750,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 5,
                'position'   => 'W0',
                'min'        => -5,
                'max'        => 0,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1199,
                'y'          => 730,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 6,
                'position'   => 'W3R',
                'min'        => -3.5,
                'max'        => 1.5,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1609,
                'y'          => 560,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 7,
                'position'   => 'L44+80',
                'min'        => -0.3,
                'max'        => 1.1,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1629,
                'y'          => 420,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 8,
                'position'   => 'L42',
                'min'        => -1.05,
                'max'        => 0.35,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1619,
                'y'          => 310,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 9,
                'position'   => 'W5R+50',
                'min'        => -1,
                'max'        => 0.4,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 909,
                'y'          => 310,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 10,
                'position'   => 'W0',
                'min'        => -2,
                'max'        => 2,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 259,
                'y'          => 540,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 11,
                'position'   => 'W5L',
                'min'        => -3,
                'max'        => 1,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 813,
                'y'          => 693,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 12,
                'position'   => 'W0',
                'min'        => -3,
                'max'        => 1,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1443,
                'y'          => 623,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 13,
                'position'   => 'W5R',
                'min'        => -4,
                'max'        => 1,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 105,
                'y'          => 580,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 14,
                'position'   => 'H16+40',
                'min'        => -0.5,
                'max'        => 2.5,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1599,
                'y'          => 630,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 15,
                'position'   => 'H16+40',
                'min'        => -0.5,
                'max'        => 2.5,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 255,
                'y'          => 438,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 16,
                'position'   => 'L44',
                'min'        => -3,
                'max'        => 1,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1531,
                'y'          => 487,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 17,
                'position'   => 'L44',
                'min'        => -3,
                'max'        => 1,
                'pt_pn'      => 6441211020,
                'figure_id'  => $getFigureId(6441211020, 'molding'),
                'created_at' => $now,
                'updated_at' => $now
            ],



            //接着：精度検査：ドアASSY RH
            [
                'x'          => 290,
                'y'          => 896,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 1,
                'position'   => 'L20',
                'min'        => -1,
                'max'        => 1.5,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 573,
                'y'          => 893,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 2,
                'position'   => 'L22',
                'min'        => -1,
                'max'        => 1.5,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 873,
                'y'          => 888,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 3,
                'position'   => 'L25',
                'min'        => -1,
                'max'        => 1.5,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1197,
                'y'          => 878,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 4,
                'position'   => 'L27',
                'min'        => -1,
                'max'        => 1.5,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1424,
                'y'          => 759,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 5,
                'position'   => 'H12',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1533,
                'y'          => 625,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 6,
                'position'   => 'H13',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1598,
                'y'          => 445,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 7,
                'position'   => 'H14+50',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1617,
                'y'          => 302,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 8,
                'position'   => 'H15+50',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1240,
                'y'          => 188,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 9,
                'position'   => 'L28+37.7',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 892,
                'y'          => 201,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 10,
                'position'   => 'L23+53',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 502,
                'y'          => 227,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 11,
                'position'   => 'L20+29.7',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 756,
                'y'          => 819,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 12,
                'position'   => 'L23+70',
                'min'        => -0.3,
                'max'        => 1.7,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1441,
                'y'          => 782,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 13,
                'position'   => 'H12',
                'min'        => -1.6,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1458,
                'y'          => 765,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 14,
                'position'   => 'H12',
                'min'        => -2,
                'max'        => 0.5,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1553,
                'y'          => 643,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 15,
                'position'   => 'H13',
                'min'        => -1.6,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1565,
                'y'          => 627,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 16,
                'position'   => 'H13',
                'min'        => -2,
                'max'        => 0.5,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1629,
                'y'          => 434,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 17,
                'position'   => 'H14+50',
                'min'        => -1.9,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1626,
                'y'          => 457,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 18,
                'position'   => 'H14+50',
                'min'        => -2,
                'max'        => 0.5,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1646,
                'y'          => 311,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 19,
                'position'   => 'H15+50',
                'min'        => -1.9,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1646,
                'y'          => 288,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 20,
                'position'   => 'H15+50',
                'min'        => -2,
                'max'        => 0.5,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1427,
                'y'          => 233,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 21,
                'position'   => 'H12',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 323,
                'y'          => 138,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 22,
                'position'   => 'L20+30',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 292,
                'y'          => 191,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 23,
                'position'   => 'L20',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701511020,
                'figure_id'  => $getFigureId(6701511020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],





            //接着：精度検査：ドアASSY LH
            [
                'x'          => 1470,
                'y'          => 896,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 1,
                'position'   => 'L20',
                'min'        => -1,
                'max'        => 1.5,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1168,
                'y'          => 893,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 2,
                'position'   => 'L22',
                'min'        => -1,
                'max'        => 1.5,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 868,
                'y'          => 888,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 3,
                'position'   => 'L25',
                'min'        => -1,
                'max'        => 1.5,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 544,
                'y'          => 878,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 4,
                'position'   => 'L27',
                'min'        => -1,
                'max'        => 1.5,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 317,
                'y'          => 759,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 5,
                'position'   => 'H12',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 208,
                'y'          => 625,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 6,
                'position'   => 'H13',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 143,
                'y'          => 445,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 7,
                'position'   => 'H14+50',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 124,
                'y'          => 302,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 8,
                'position'   => 'H15+50',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 501,
                'y'          => 188,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 9,
                'position'   => 'L28+37.7',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 849,
                'y'          => 201,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 10,
                'position'   => 'L23+53',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1239,
                'y'          => 227,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 11,
                'position'   => 'L20+29.7',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 985,
                'y'          => 819,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 12,
                'position'   => 'L23+70',
                'min'        => -0.3,
                'max'        => 1.7,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 300,
                'y'          => 782,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 13,
                'position'   => 'H12',
                'min'        => -1.6,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 283,
                'y'          => 765,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 14,
                'position'   => 'H12',
                'min'        => -2,
                'max'        => 0.5,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 188,
                'y'          => 643,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 15,
                'position'   => 'H13',
                'min'        => -1.6,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 176,
                'y'          => 627,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 16,
                'position'   => 'H13',
                'min'        => -2,
                'max'        => 0.5,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 112,
                'y'          => 434,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 17,
                'position'   => 'H14+50',
                'min'        => -1.9,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 115,
                'y'          => 457,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 18,
                'position'   => 'H14+50',
                'min'        => -2,
                'max'        => 0.5,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 95,
                'y'          => 311,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 19,
                'position'   => 'H15+50',
                'min'        => -1.9,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 95,
                'y'          => 288,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 20,
                'position'   => 'H15+50',
                'min'        => -2,
                'max'        => 0.5,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 314,
                'y'          => 233,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 21,
                'position'   => 'H12',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1418,
                'y'          => 138,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 22,
                'position'   => 'L20+30',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1449,
                'y'          => 191,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'right',
                'label'      => 23,
                'position'   => 'L20',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6701611020,
                'figure_id'  => $getFigureId(6701611020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],





            //接着：精度検査：ラゲージインナASSY STD
            [
                'x'          => 248,
                'y'          => 124,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 1,
                'position'   => 'W5L+50',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 165,
                'y'          => 336,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 2,
                'position'   => 'L42',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 148,
                'y'          => 616,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 3,
                'position'   => 'L44+80',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 525,
                'y'          => 856,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 4,
                'position'   => 'W3L',
                'min'        => -1.2,
                'max'        => 1.3,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 873,
                'y'          => 887,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 5,
                'position'   => 'W0',
                'min'        => -1.2,
                'max'        => 1.3,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1213,
                'y'          => 857,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 6,
                'position'   => 'W3R',
                'min'        => -1.2,
                'max'        => 1.3,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1593,
                'y'          => 617,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 7,
                'position'   => 'L44+80',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1579,
                'y'          => 344,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 8,
                'position'   => 'L42',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1493,
                'y'          => 124,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 9,
                'position'   => 'W5R+50',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 872,
                'y'          => 255,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 10,
                'position'   => 'W0',
                'min'        => -3,
                'max'        => 3,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 344,
                'y'          => 614,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 11,
                'position'   => 'W5L',
                'min'        => -3,
                'max'        => 3,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1404,
                'y'          => 614,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 12,
                'position'   => 'W5R',
                'min'        => -3,
                'max'        => 3,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 154,
                'y'          => 674,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 13,
                'position'   => 'H16+40',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1594,
                'y'          => 674,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 14,
                'position'   => 'H16+40',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 294,
                'y'          => 414,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 15,
                'position'   => 'L44',
                'min'        => -3,
                'max'        => 3,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1444,
                'y'          => 414,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 16,
                'position'   => 'L44',
                'min'        => -3,
                'max'        => 3,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 154,
                'y'          => 284,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 17,
                'position'   => 'L42',
                'min'        => -4,
                'max'        => 6,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 134,
                'y'          => 564,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 18,
                'position'   => 'L44+80',
                'min'        => -4,
                'max'        => 6,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 874,
                'y'          => 924,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 19,
                'position'   => 'W0',
                'min'        => -4,
                'max'        => 6,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1604,
                'y'          => 564,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 20,
                'position'   => 'L44+80',
                'min'        => -4,
                'max'        => 6,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1584,
                'y'          => 284,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 21,
                'position'   => 'L42',
                'min'        => -4,
                'max'        => 6,
                'pt_pn'      => 6440111010,
                'figure_id'  => $getFigureId(6440111010, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],


            
            //接着：精度検査：ラゲージインナASSY ARW
            [
                'x'          => 248,
                'y'          => 124,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 1,
                'position'   => 'W5L+50',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 165,
                'y'          => 336,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 2,
                'position'   => 'L42',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 148,
                'y'          => 616,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 3,
                'position'   => 'L44+80',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 525,
                'y'          => 856,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 4,
                'position'   => 'W3L',
                'min'        => -1.2,
                'max'        => 1.3,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 873,
                'y'          => 887,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 5,
                'position'   => 'W0',
                'min'        => -1.2,
                'max'        => 1.3,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1213,
                'y'          => 857,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 6,
                'position'   => 'W3R',
                'min'        => -1.2,
                'max'        => 1.3,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1593,
                'y'          => 617,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 7,
                'position'   => 'L44+80',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1579,
                'y'          => 344,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 8,
                'position'   => 'L42',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1493,
                'y'          => 124,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 9,
                'position'   => 'W5R+50',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 872,
                'y'          => 255,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 10,
                'position'   => 'W0',
                'min'        => -3,
                'max'        => 3,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 344,
                'y'          => 614,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 11,
                'position'   => 'W5L',
                'min'        => -3,
                'max'        => 3,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1404,
                'y'          => 614,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 12,
                'position'   => 'W5R',
                'min'        => -3,
                'max'        => 3,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 154,
                'y'          => 674,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 13,
                'position'   => 'H16+40',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1594,
                'y'          => 674,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 14,
                'position'   => 'H16+40',
                'min'        => -1,
                'max'        => 1,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 294,
                'y'          => 414,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 15,
                'position'   => 'L44',
                'min'        => -3,
                'max'        => 3,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1444,
                'y'          => 414,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 16,
                'position'   => 'L44',
                'min'        => -3,
                'max'        => 3,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 154,
                'y'          => 284,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 17,
                'position'   => 'L42',
                'min'        => -4,
                'max'        => 6,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 134,
                'y'          => 564,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 18,
                'position'   => 'L44+80',
                'min'        => -4,
                'max'        => 6,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 874,
                'y'          => 924,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 19,
                'position'   => 'W0',
                'min'        => -4,
                'max'        => 6,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1604,
                'y'          => 564,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 20,
                'position'   => 'L44+80',
                'min'        => -4,
                'max'        => 6,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],[
                'x'          => 1584,
                'y'          => 284,
                'lx'         => 10,
                'ly'         => 10,
                'side'       => 'left',
                'label'      => 21,
                'position'   => 'L42',
                'min'        => -4,
                'max'        => 6,
                'pt_pn'      => 6440111020,
                'figure_id'  => $getFigureId(6440111020, 'jointing'),
                'created_at' => $now,
                'updated_at' => $now
            ],
        ];

        DB::connection('950A')->table($table_name)->insert($data);

        if (env('DB_CONNECTION') == 'mysql') {
            DB::connection('950A')->statement('SET FOREIGN_KEY_CHECKS=1;');
        }
    }
}